config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/y', as: 'rails_admin'
  resources :groups
  resources :courses
  get 'welcome/index'
  resources :teachers do
    collection do
      get :gradeinputshow
      get :gradeinput
      get :coursesetshow
      get :courseset
    end
  end
  resources :students do
    collection do
      get :getstuwei
    end
  end
  root 'welcome#index'
  resources :search do
    collection do
      get :searchbysno
      get :searchbynm
      get :searchbymno
    end
  end
  # scope '/majors' do
  #   resources :majors
  #   get '/majors/:id/addcourse', to: 'majors#addcourse'
  # end
  resources :majors do
    member do
      post '/addcourse', to: 'majors#addcoursepost', as: 'addcoursepost'
    end
    collection do
      get '/:id/addcourse', to: 'majors#addcourse', as: 'addcourse'
      get '/:id/showcoursesofmajor', to: 'majors#showcoursesofmajor', as: 'showcoursesofmajor'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  has_many :students_courses,class_name: 'StudentsCourses'
  #通过另一个关联关系找到一堆的课程
  has_many :courses, through: :students_courses
end

app/controllers/students_controller.rb
require 'set'
class StudentsController < ApplicationController

  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  def getstuwei
    # json=Hash.new
    # msg=Hash.new
    @stus=Set[]
    # @stus=Hash.new
    students = Student.all
    students.each do |stu|
      items=StudentsCourses.where(student_id: stu.id)
      comcre=0
      optcre=0
      major=stu.group.major
      items.each do |item|
        mc = MajorsCourses.where('major_id = ? AND course_id = ? ',major.id,item.course_id ).first
        if item.grade<60
          if mc.compulsory
            comcre=comcre+mc.credit
          else
            optcre=optcre+mc.credit
          end
        end
      end
      if comcre >= 10 || optcre >= 15
        # 已经退学了
        next
      end
      if comcre >= 7  || optcre >= 12
        # j={
        #     name: stu.name,
        #     stuno: stu.stuno,
        #     birth: stu.birth,
        #     male: stu.male,
        #     group_id: stu.group_id
        # }
        # msg=msg.merge(stu.id => j)
        @stus << stu
        # @stus=@stus.merge(stu.id => stu)

      end
    end
    if !@stus.empty?
      respond_to do |format|
        format.js { render partial: 'students/result' }
      end
    else
      respond_to do |format|
        format.js { render partial: 'students/empty' }
      end
    end
  end

  #   json=json.merge(:msg => msg)
  #   if msg.empty?
  #     json=json.merge(:status => 'empty')
  #     render json: json
  #   else
  #     json=json.merge(:status => 'err')
  #     render json: json
  #   end

  # GET /students/1 or /students/1.json
  def show
    #不如让我们在这里把他查出来得了
    # 查询一位学生所修的课程、性质（必修或选修）、学期、学分及成绩；---查询他的必修课平均成绩、所有课程平均成绩（平均成绩应按学分加权）
    #这是当前页面的学生
    # 操你妈的傻逼rails
    # 假设一个班不会在不同时间同上一门课
    @items=StudentsCourses.where(student_id: @student.id)
    @courses=@student.courses # 这个同学
    @major=@student.group.major
    @comans=0
    @allans=0
    sumcrecom=0
    sumcre=0
    # 关于当前学生的所有成绩记录
    @items.each do |item|
      # notice: the result of 'where' is a set
      mc = MajorsCourses.where('major_id = ? AND course_id = ? ',@major.id,item.course_id ).first
      # cour=Course.find item.course_id
      if mc.compulsory
        @comans=@comans+mc.credit*item.grade
        sumcrecom=sumcrecom+mc.credit
      end
      @allans=@allans+mc.credit*item.grade
      sumcre=sumcre+mc.credit
      #对于每一个item都有一个course_id,根据这个寻找带了这个课的老师即可
    end
    if sumcrecom!=0
      @comans=@comans/sumcrecom
    end
    if sumcre!=0
      @allans=@allans/sumcre
    end

    #被哪些教师带过(不能重复)
    @result = Set[]
    @TC=TeachersCourses.where(group_id: @student.group_id)
    @TC.each do |t|
      @result << t.teacher_id
    end

    #先链接，再多条件查询，再使用集函数,除法运算只要有一个是浮点数那么结果就是一个浮点数
    # @conans=Course.joins("INNER JOIN students_courses ON students_courses.course_id=courses.id").
    # sumconcredit=StudentsCourses.joins("INNER JOIN courses ON course_id=courses.id").
    #     where("student_id = ? AND compulsory = ?",@student.id,true).sum(:credit)
    # @conans=sumcon/sumconcredit
    # sumall=StudentsCourses.where(:student_id ==@student.id).average(:grade)
    # sumallcredit=StudentsCourses.joins("INNER JOIN courses ON course_id=courses.id").
    #     where("student_id = ?",@student.id).sum(:credit)
    # @allans=sumall/sumallcredit
    # StudentsCourses.where(:student_id==2 AND Courses.conpulsory==true)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :stuno, :birth, :male,:group_id )
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_empty.html.erb
<!--<p class="text-center">-->
<!--  <h5>未找到对应信息</h5>-->
<!--</p>-->
未找到对应信息

app/views/students/_empty.js.erb
document.querySelector("#results").innerHTML= '<%=j render 'students/empty.html' %>'

app/views/students/_form.html.erb
  <%= form_with(model: student) do |form| %>
    <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
          <% student.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name,:class=>"form-control" %>
    </div>

    <div class="field">
      <%= form.label :stuno %>
      <%= form.text_field :stuno,:class=>"form-control" %>
    </div>

    <div class="field">
      <%= form.label :birth %>
      <%= form.text_field :birth,:class=>"form-control" %>
    </div>

    <div class="field">
      <%= form.label :male %>
      <%= form.text_field :male,:class=>"form-control" %>
    </div>

    <div class="field">
      <%= form.label :group_id %>
      <%= form.text_field :group_id,:class=>"form-control" %>
    </div>

    <div class="actions">
      <%= form.submit 'save', :class=>"btn btn-primary"%>
    </div>
  <% end %>

app/views/students/_result.html.erb
<% if @stus %>
  <% @stus.each do |stu| %>
  <strong>姓名：</strong><%= stu.name %>
  <strong>学号：</strong><%= stu.stuno %>
  <strong>出生日期：</strong><%= stu.birth %>
  <strong>性别：</strong><%= stu.male ? '男' : '女' %>
  <strong>班级：</strong><%= Group.find(stu.group_id).name %>
    <br>
  <% end %>
<% end %>

app/views/students/_result.js.erb
document.querySelector("#results").innerHTML= '<%=j render 'students/result.html' %>'

app/views/students/_srchrs.html.erb
<% if @stus %>
  <% @stus.each do |stu| %>
  <strong>姓名：</strong><%= stu.name %>
  <strong>学号：</strong><%= stu.stuno %>
  <strong>出生日期：</strong><%= stu.birth %>
  <strong>性别：</strong><%= stu.male %>
  <strong>班级：</strong><%= stu.group_id %>
    <br>
  <% end %>
<% end %>

app/views/students/edit.html.erb
<div class="container ">
  <h1>Editing Student</h1>

  <%= render 'form', student: @student %>

  <%= link_to 'Show', @student, :class=>"btn btn-light" %> |
  <%= link_to 'Back', students_path , :class=>"btn btn-secondary text-white" %>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<%= form_tag   getstuwei_students_path, method: :get,remote: true,class: 'srch' do  %>

  <div class="actions"  >
    <%#= submit_tag '查询即将退学学生',:class => 'btn btn-danger'%>
    <input type="submit" name="commit" value="查询即将退学学生"
           class="btn btn-danger" data-toggle="modal"
           data-target="#staticBackdrop" data-disable-with="查询即将退学学生">
  </div>

<%end %>

<table class="table table-striped  text-center">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Stuno</th>
      <th scope="col">Birth</th>
      <th scope="col">Sex</th>
      <th scope="col">Group_id</th>
      <th scope="col"></th>
      <th scope="col">Option</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.stuno %></td>
        <td><%= student.birth %></td>
        <td><%= student.male ? '男' : '女' %></td>
        <td><%= student.group.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class='container pb-5'>
  <div class="row">

  <%= form_tag   searchbysno_search_index_path, method: :get,remote: true ,:class=>'col' do %>
    <div class="field">
      <%= text_field_tag :stuno, nil , placeholder:'学号',:class=>"form-control" %>
    </div>
    <div class="actions ">
      <%#= submit_tag '根据学号查询'%>
      <input type="submit" name="commit" value="根据学号查询"
             class="btn btn-primary" data-toggle="modal"
             data-target="#staticBackdrop" data-disable-with="根据学号查询">
    </div>
  <%end %>

  <%= form_tag   searchbynm_search_index_path, method: :get,remote: true,:class=>'col' do  %>
    <div class="field">
      <%= text_field_tag :name, nil , placeholder:'姓名',:class=>"form-control" %>
    </div>
    <div class="actions">
      <%#= submit_tag '根据姓名查询'%>
      <input type="submit" name="commit" value="根据姓名查询"
             class="btn btn-primary" data-toggle="modal"
             data-target="#staticBackdrop" data-disable-with="根据姓名查询">
    </div>
  <%end %>


  <%= form_tag   searchbymno_search_index_path, method: :get,remote: true,:class=>'col' do  %>
    <div class="field">
      <%= text_field_tag :mno, nil , placeholder:'专业号',:class=>"form-control" %>
    </div>
    <div class="actions">
      <%#= submit_tag '根据专业号查询'%>
      <input type="submit" name="commit" value="根据专业号查询"
             class="btn btn-primary" data-toggle="modal"
             data-target="#staticBackdrop" data-disable-with="根据专业号查询">
    </div>
  <%end %>

  </div>


  <%= link_to 'New Student', new_student_path,:class=>"btn btn-success" %>
</div>




<!--<div id="srchbysno">-->
  <%#=render 'students/result' %>
<!--</div>-->



<!--<div id="srchbysno">-->
  <%#=render 'students/result' %>
<!--</div>-->


<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">-->
<!--  Launch static backdrop modal-->
<!--</button>-->

<!-- Modal 模态框-->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">查询结果</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="results">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
<!--        <button type="button" class="btn btn-primary">Understood</button>-->
      </div>
    </div>
  </div>
</div>


<%#= content_for :javascripts do %>
<!--  <script type="text/javascript">-->
<!--    // alert('232222');-->
<!--    $(".srch").on("ajax:success",function(event,data) {-->
<!--        alert('111');-->
<!--      if (data.status == 'ok'){-->
<!--          alert("1111111");-->
<!--      }-->
<!--      else{-->
<!--          alert(data.msg);-->
<!--      }-->
<!--    });-->
<!--  </script>-->
<%#end -%>

app/views/students/new.html.erb
<div class="container ">
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, :class=>"btn btn-light" %>
</div>

app/views/students/show.html.erb
<div class="container">
  <h2>学生信息页</h2>

  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @student.name %>
  </p>

  <p>
    <strong>Stuno:</strong>
    <%= @student.stuno %>
  </p>

  <p>
    <strong>birth:</strong>
    <%= @student.birth %>
  </p>

  <p>
    <strong>male:</strong>
    <%= @student.male ? '男' : '女' %>
  </p>

  <p>
    <strong>group:</strong>
    <%= @student.group.name %>
  </p>

  <p>
    <strong>major:</strong>
    <%= @student.group.major.name %>
  </p>

  <table class="table table-hover ">
    <thead>
    <tr>
      <th>Course Name</th>
      <th>Course Nature</th>
      <th>Start Time</th>
      <th>Credit</th>
      <th>Grade</th>
      <th>Make Up</th>
      <th colspan="6"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <%mc=MajorsCourses.where('major_id = ? AND course_id = ? ',@major.id,course.id ).first %>
        <td><%= course.name %></td>
        <td><%= mc.compulsory ? '必修' : '选修' %></td>
        <td><%= MajorsCourses.find_by(course_id: course.id,major_id: @student.group.major.id).start_time %></td>
        <td><%= mc.credit %></td>
        <% sc=StudentsCourses.joins("INNER JOIN courses ON course_id=courses.id").
            where("course_id = ? AND student_id = ?" , course.id , @student.id).first%>
        <td><%= sc.grade %></td>
        <%if sc.grade<60 %>
          <td><%= sc.make_up ? '已补考' : '未补考' %></td>
        <%else%>
          <td>通过</td>
        <%end%>
      </tr>
    <% end %>
    </tbody>
  </table>


<br>


  <tr>
    <td>必修课加权成绩: <%= @comans %></td>
    <br>
    <td>全部课程加权成绩: <%= @allans %></td>
  </tr>

  <p class="le">
    任课老师:
    <%@result.each do |rs| %>
      <%=link_to Teacher.find(rs).name, teacher_path(rs) %>
    <% end %>
  </p>
  <%= link_to 'Edit', edit_student_path(@student),:class => 'btn btn-success' %>
  <%= link_to 'Back', students_path , :class => 'btn btn-secondary text-white ' %>

</div>