config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/y', as: 'rails_admin'
  resources :groups
  resources :courses
  get 'welcome/index'
  resources :teachers do
    collection do
      get :gradeinputshow
      get :gradeinput
      get :coursesetshow
      get :courseset
    end
  end
  resources :students do
    collection do
      get :getstuwei
    end
  end
  root 'welcome#index'
  resources :search do
    collection do
      get :searchbysno
      get :searchbynm
      get :searchbymno
    end
  end
  # scope '/majors' do
  #   resources :majors
  #   get '/majors/:id/addcourse', to: 'majors#addcourse'
  # end
  resources :majors do
    member do
      post '/addcourse', to: 'majors#addcoursepost', as: 'addcoursepost'
    end
    collection do
      get '/:id/addcourse', to: 'majors#addcourse', as: 'addcourse'
      get '/:id/showcoursesofmajor', to: 'majors#showcoursesofmajor', as: 'showcoursesofmajor'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/major.rb
class Major < ApplicationRecord

  has_many :groups
  has_many :teachers

  has_many :majors_courses,class_name: 'MajorsCourses'
  has_many :courses, through: :majors_courses

end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: %i[ show edit update destroy addcourse ]


  # addcourse_majors_path
  def showcoursesofmajor
    @major=Major.find(params[:id])
    @courses=@major.courses
    if @courses
      respond_to do |format|
        format.js { render partial: 'majors/result' }
      end
    end
    # @MC=MajorsCourses.find_by_major_id(@major.id)
  end
  def addcourse
    @major=Major.find(params[:id])
  end

  # addcoursepost_majors
  def addcoursepost
    @item=MajorsCourses.new
    @item.major_id = params[:id]
    @major = Major.find(params[:id])
    # @major=Major.find(params[:id])
    course = Course.find_by_cno(params[:cno])
    @item.course_id = course.id
    @item.compulsory = params[:compulsory]
    @item.credit = params[:credit]
    @item.start_time = params[:start_time]
    if @item.save
      redirect_to  major_path(@major)
    else
      redirect_to addcourse_majors_path
    end
  end

  # GET /majors or /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1 or /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors or /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to major_url(@major), notice: "Major was successfully created." }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1 or /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to major_url(@major), notice: "Major was successfully updated." }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1 or /majors/1.json
  def destroy
    @major.destroy

    respond_to do |format|
      format.html { redirect_to majors_url, notice: "Major was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def major_params
      params.require(:major).permit(:name, :mno)
    end
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/views/majors/_form.html.erb
<%= form_with(model: major) do |form| %>
  <% if major.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>

      <ul>
        <% major.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mno %>
    <%= form.text_field :mno %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/majors/_result.html.erb
<p id="notice"><%= notice %></p>

<h4><%=@major.name %></h4>

<table>
  <thead>
  <tr>
    <th>课程</th>
    <th>课程号</th>
    <th>性质</th>
    <th>学分</th>
    <th>开设时间</th>
    <th>详情</th>
    <th colspan="6"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.cno %></td>
      <td><%= MajorsCourses.where('major_id = ? AND course_id = ? ',@major.id,c.id ).first.compulsory ? '必修': '选修' %></td>
      <td><%= MajorsCourses.where('major_id = ? AND course_id = ? ',@major.id,c.id ).first.credit %></td>
      <td><%= MajorsCourses.where('major_id = ? AND course_id = ? ',@major.id,c.id ).first.start_time %></td>
      <td><%= link_to 'show',course_path(c) %></td>
<!--      <td><%#= link_to 'Show', major %></td>-->
<!--      <td><%#= link_to 'Edit', edit_major_path(major) %></td>-->
<!--      <td><%#= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%#= link_to 'Back', @major %>
<%#= link_to 'New Major', new_major_path %>

app/views/majors/_result.js.erb
document.querySelector("#results").innerHTML= '<%=j render 'majors/result.html' %>'

app/views/majors/addcourse.html.erb
<div class="container pb-5">
  <h1>Add Course</h1>

  <%= form_tag  addcoursepost_major_path, method: 'post' do  %>

    <div class="field">
      <%= text_field_tag :cno, nil , placeholder:'课程号' ,:class=>"form-control"%>
    </div>

    <div class="field">
      <%= text_field_tag :compulsory, nil , placeholder:'是否必修' ,:class=>"form-control"%>
    </div>

    <div class="field">
      <%= text_field_tag :credit, nil , placeholder:'学分' ,:class=>"form-control"%>
    </div>

    <div class="field">
      <%= text_field_tag :start_time, nil , placeholder:'开课时间' ,:class=>"form-control"%>
    </div>

    <div class="actions srch">
      <%= submit_tag '添加', :class=>"btn btn-primary" %>
    </div>

  <%end %>

  <%#= form_with(model: Major) do |form| %>
    <%# if major.errors.any? %>
  <!--    <div id="error_explanation">-->
  <!--      <h2><%#= pluralize(major.errors.count, "error") %> prohibited this major from being saved:</h2>-->

  <!--      <ul>-->
          <%# major.errors.each do |error| %>
  <!--          <li><%#= error.full_message %></li>-->
          <%# end %>
  <!--      </ul>-->
  <!--    </div>-->
    <%# end %>


  <!--  <div class="hidden">-->
      <%#= form.hidden_label 'major' %>
      <%#= form.hidden_field :major_id => @major.id %>
  <!--  </div>-->

  <!--  <div class="field">-->
      <%#= form.label :course_id %>
      <%#= form.text_field :course_id %>
  <!--  </div>-->

  <!--  <div class="field">-->
      <%#= form.label :compulsory %>
      <%#= form.text_field :compulsory %>
  <!--  </div>-->

  <!--  <div class="field">-->
      <%#= form.label :credit %>
      <%#= form.text_field :credit %>
  <!--  </div>-->

  <!--  <div class="actions">-->
      <%#= form.submit %>
  <!--  </div>-->
  <%# end %>


  <%= link_to 'Back', @major ,:class => 'btn btn-light'%>
</div>

app/views/majors/edit.html.erb
<h1>Editing Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Show', @major %> |
<%= link_to 'Back', majors_path %>

app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Majors</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Mno</th>
      <th></th>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= major.name %></td>
        <td><%= major.mno %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path ,:class=>"btn btn-success" %>

app/views/majors/new.html.erb
<h1>New Major</h1>

<%= render 'form', major: @major %>

<%= link_to 'Back', majors_path %>

app/views/majors/show.html.erb
<div class="container">
  <h2>专业信息页</h2>
<%#addp= '/majors/'+@major.id.to_s+'/addcourse'%>
  <%= link_to 'add course', addcourse_majors_path,:class => 'btn btn-outline-success my-2 my-sm-0' %>
<!--  <input type="submit" name="commit" value="根据姓名查询"-->
<!--         class="btn btn-primary" data-toggle="modal"-->
<!--         data-target="#staticBackdrop" data-disable-with="根据姓名查询">-->
  <button type="submit" name="commit" value="根据姓名查询"
          class="btn btn-light" data-toggle="modal"
          data-target="#staticBackdrop" data-disable-with="根据姓名查询">
    <%= link_to 'all courses', showcoursesofmajor_majors_path ,remote: true%>

  </button>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @major.name %>
  </p>

  <p>
    <strong>Mno:</strong>
    <%= @major.mno %>
  </p>

  <%= link_to 'Edit', edit_major_path(@major),:class => 'btn btn-success'  %>
  <%= link_to 'Back', majors_path, :class => 'btn btn-secondary text-white ' %>

</div>

<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">查询结果</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="results">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
        <!--        <button type="button" class="btn btn-primary">Understood</button>-->
      </div>
    </div>
  </div>
</div>

app/views/majors/showcoursesofmajor.html.erb
<p id="notice"><%= notice %></p>

<h1>Majors: <%=@major.name %></h1>

<table>
  <thead>
  <tr>
    <th>Course Name</th>
    <th>Course Number</th>
    <th>Compulsory</th>
    <th>Credit</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.cno %></td>
      <td><%= MajorsCourses.find_by_course_id(c.id).compulsory %></td>
      <td><%= MajorsCourses.find_by_course_id(c.id).credit %></td>
<!--      <td><%#= link_to 'Show', major %></td>-->
<!--      <td><%#= link_to 'Edit', edit_major_path(major) %></td>-->
<!--      <td><%#= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', @major %>
<%#= link_to 'New Major', new_major_path %>