config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/y', as: 'rails_admin'
  resources :groups
  resources :courses
  get 'welcome/index'
  resources :teachers do
    collection do
      get :gradeinputshow
      get :gradeinput
      get :coursesetshow
      get :courseset
    end
  end
  resources :students do
    collection do
      get :getstuwei
    end
  end
  root 'welcome#index'
  resources :search do
    collection do
      get :searchbysno
      get :searchbynm
      get :searchbymno
    end
  end
  # scope '/majors' do
  #   resources :majors
  #   get '/majors/:id/addcourse', to: 'majors#addcourse'
  # end
  resources :majors do
    member do
      post '/addcourse', to: 'majors#addcoursepost', as: 'addcoursepost'
    end
    collection do
      get '/:id/addcourse', to: 'majors#addcourse', as: 'addcourse'
      get '/:id/showcoursesofmajor', to: 'majors#showcoursesofmajor', as: 'showcoursesofmajor'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :major
  has_many :teachers_courses,class_name: 'TeachersCourses'
  #通过另一个关联关系找到一堆的课程
  has_many :courses, through: :students_courses
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]


  def gradeinputshow
    @SC=StudentsCourses.all
  end

  def gradeinput
    # @SC=StudentsCourses.all
    @item=StudentsCourses.new
    @stu=Student.find_by_stuno(params[:stuno])
    c=Course.find_by_cno(params[:cno])
    #find_by只返回找到的第一个值，但是这就够了
    @rs=TeachersCourses.find_by(group_id: @stu.group.id, course_id: c.id)
    #如果没有找到的话就返回，否则保存
    if !@rs
      #说明还没有开设课程,返回到课程开设列表
      redirect_to coursesetshow_teachers_path
    else
      sc=StudentsCourses.find_by(student_id: @stu.id,course_id: c.id)
      # 如果可以找到已有的成绩记录并且小于60分并且没有补考
      if sc && sc.grade<60 && !sc.make_up
        sc.update_attribute(:grade,params[:grade])
        sc.update_attribute(:make_up,true)
      end
      # 说明是第一次成绩录入,插入一条记录
      if !sc
        @item.student_id=@stu.id
        @item.course_id = c.id
        @item.grade=params[:grade]
        @item.make_up=false
        @item.save
      end
      redirect_to gradeinputshow_teachers_path
    end

    # if @item.save
    #    redirect_to gradeinputshow_teachers_path, notice: "Teacher was successfully created."
    # end
    # redirect_to gradeinputshow_teachers_path
  end

  def coursesetshow
    @SC=TeachersCourses.all
  end
  def courseset
    @item=TeachersCourses.new
    t = Teacher.find_by_name(params[:teacher_name])
    @item.teacher_id = t.id
    g = Group.find_by_gno(params[:gno])
    @item.group_id = g.id
    c = Course.find_by_cno(params[:cno])
    @item.course_id = c.id

    @rs=MajorsCourses.find_by(major_id: g.major.id, course_id: c.id)
    # 如果这个班计划里有这门课，那就可以开课
    if @rs
      @item.save
      redirect_to coursesetshow_teachers_path
    else
      # 否则就要去对应的专业先开这门课
      redirect_to addcourse_majors_path(g.major)
    end
  end

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:name, :tno,:major_id)
    end

    # def item_params
    #   params.require(:item).permit(:student_id, :course_id,:grade)
    # end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="container ">
  <%= form_with(model: teacher) do |form| %>
    <% if teacher.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

        <ul>
          <% teacher.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name,:class=>"form-control"  %>
    </div>

    <div class="field">
      <%= form.label :tno %>
      <%= form.text_field :tno,:class=>"form-control"  %>
    </div>

    <div class="field">
      <%= form.label :major_id %>
      <%= form.text_field :major_id,:class=>"form-control"  %>
    </div>

    <div class="actions">
      <%= form.submit 'save', :class=>"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/teachers/coursesetshow.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Courses Offered</h1>

<table class="table text-center table-hover">
  <thead>
  <tr>
    <th>Teacher</th>
    <th>Group</th>
    <th>Course</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @SC.each do |items| %>
    <tr>
      <td><%= Teacher.find(items.teacher_id).name %></td>
      <td><%= Group.find(items.group_id).name%></td>
      <td><%= Course.find(items.course_id).name %></td>
      <!--      <td><%#= link_to 'Show', teacher %></td>-->
      <!--      <td><%#= link_to 'Edit', edit_teacher_path(teacher) %></td>-->
      <!--      <td><%#= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Teacher', new_teacher_path %>


  <%= form_tag   courseset_teachers_path, method: :get,
                 class: 'srch2' do  %>

    <div class="field">
      Teacher Name
      <%= text_field_tag :teacher_name, nil , placeholder:'老师姓名' ,:class=>"form-control"%>
    </div>

    <div class="field">
      Group Number
      <%= text_field_tag :gno, nil , placeholder:'班号',:class=>"form-control" %>
    </div>

    <div class="field">
      Course Number
      <%= text_field_tag :cno, nil , placeholder:'课程号',:class=>"form-control" %>
    </div>

<!--    <div class="field">-->
<!--      Start Time-->
      <%#= text_field_tag :start_time, nil , placeholder:'开设时间',:class=>"form-control" %>
<!--    </div>-->

    <div class="actions srch">
      <%= submit_tag '提交', :class=>"btn btn-primary"%>
    </div>

  <%end %>
</div>

app/views/teachers/edit.html.erb
<div class="container">
  <h1>Editing Teacher</h1>

  <%= render 'form', teacher: @teacher %>

  <%= link_to 'Show', @teacher, :class=>"btn btn-light" %>
  <%= link_to 'Back', teachers_path, :class=>"btn btn-secondary text-white"  %>
</div>

app/views/teachers/gradeinputshow.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Grades Input</h1>

<table class="table table-hover text-center">
  <thead>
  <tr>
    <th>Name</th>
    <th>Course</th>
    <th>Grade</th>
    <th>Make Up</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @SC.each do |items| %>
    <tr>
      <td><%= Student.find(items.student_id).name %></td>
      <td><%= Course.find(items.course_id).name %></td>
      <td><%= items.grade %></td>
      <%if items.grade<60 %>
        <td><%= items.make_up ? '已补考' : '未补考' %></td>
      <%else%>
        <td>通过</td>
      <%end%>
<!--      <td><%#= link_to 'Show', teacher %></td>-->
<!--      <td><%#= link_to 'Edit', edit_teacher_path(teacher) %></td>-->
<!--      <td><%#= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Teacher', new_teacher_path %>


  <%= form_tag   gradeinput_teachers_path, method: :get do  %>

    <div class="field">
      <%= text_field_tag :stuno, nil , placeholder:'学号',:class=>"form-control" %>
    </div>

    <div class="field">
      <%= text_field_tag :cno, nil , placeholder:'课程号',:class=>"form-control" %>
    </div>

    <div class="field">
      <%= text_field_tag :grade, nil , placeholder:'成绩',:class=>"form-control" %>
    </div>

    <div class="actions srch">
      <%= submit_tag '提交', :class=>"btn btn-primary"%>
    </div>

  <%end %>
</div>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Tno</th>
      <th>Major_id</th>
      <th></th>
      <th>Option</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.tno %></td>
        <td><%= teacher.major_id %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path,:class=>"btn btn-success" %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<div class=" container pb-5">
  <h2>教师信息页</h2>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @teacher.name %>
  </p>

  <p>
    <strong>Tno:</strong>
    <%= @teacher.tno %>
  </p>

  <p>
    <strong>major:</strong>
    <%=link_to @teacher.major.name,major_path(@teacher.major) %>
  </p>

  <%= link_to 'Edit', edit_teacher_path(@teacher),:class => 'btn btn-success' %>
  <%= link_to 'Back', teachers_path , :class => 'btn btn-secondary text-white ' %>

</div>