config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/y', as: 'rails_admin'
  resources :groups
  resources :courses
  get 'welcome/index'
  resources :teachers do
    collection do
      get :gradeinputshow
      get :gradeinput
      get :coursesetshow
      get :courseset
    end
  end
  resources :students do
    collection do
      get :getstuwei
    end
  end
  root 'welcome#index'
  resources :search do
    collection do
      get :searchbysno
      get :searchbynm
      get :searchbymno
    end
  end
  # scope '/majors' do
  #   resources :majors
  #   get '/majors/:id/addcourse', to: 'majors#addcourse'
  # end
  resources :majors do
    member do
      post '/addcourse', to: 'majors#addcoursepost', as: 'addcoursepost'
    end
    collection do
      get '/:id/addcourse', to: 'majors#addcourse', as: 'addcourse'
      get '/:id/showcoursesofmajor', to: 'majors#showcoursesofmajor', as: 'showcoursesofmajor'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :students


  validates_uniqueness_of :cno
  validates_uniqueness_of :name


  has_many :teachers_courses,class_name: 'TeachersCourses'
  has_many :teachers,through: :teachers_courses
  #指定关联关系映射的model
  has_many :students_courses,class_name: 'StudentsCourses'
  has_many :students, through: :students_courses

  has_many :majors_courses,class_name: 'MajorsCourses'
  has_many :majors, through: :majors_courses

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :students
  belongs_to :major
end

app/models/major.rb
class Major < ApplicationRecord

  has_many :groups
  has_many :teachers

  has_many :majors_courses,class_name: 'MajorsCourses'
  has_many :courses, through: :majors_courses

end

app/models/majors_courses.rb
class MajorsCourses < ApplicationRecord

  self.table_name = 'majors_courses'

  validates_uniqueness_of :major_id,scope: [:course_id]

  validates  :course_id, presence: true
  # validates  :compulsory, presence: true
  validates  :credit, presence: true
  belongs_to :major
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group
  has_many :students_courses,class_name: 'StudentsCourses'
  #通过另一个关联关系找到一堆的课程
  has_many :courses, through: :students_courses
end

app/models/students_courses.rb
class StudentsCourses < ApplicationRecord

  self.table_name = 'students_courses'

  # validates_uniqueness_of :student_id,scope: [:course_id]
  validates :student_id, :course_id, :grade, presence: true
  belongs_to :student
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :major
  has_many :teachers_courses,class_name: 'TeachersCourses'
  #通过另一个关联关系找到一堆的课程
  has_many :courses, through: :students_courses
end

app/models/teachers_courses.rb
class TeachersCourses < ApplicationRecord

  self.table_name = 'teachers_courses'
  #四个一起才是主键,一位教师可以给多个班带课，但不能给一个班带多门课
  validates_uniqueness_of :teacher_id, scope: [:group_id]
  validates :teacher_id, :group_id, :course_id, presence: true
  belongs_to :teacher
  belongs_to :course
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :gno,:major_id)
    end
end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: %i[ show edit update destroy addcourse ]


  # addcourse_majors_path
  def showcoursesofmajor
    @major=Major.find(params[:id])
    @courses=@major.courses
    if @courses
      respond_to do |format|
        format.js { render partial: 'majors/result' }
      end
    end
    # @MC=MajorsCourses.find_by_major_id(@major.id)
  end
  def addcourse
    @major=Major.find(params[:id])
  end

  # addcoursepost_majors
  def addcoursepost
    @item=MajorsCourses.new
    @item.major_id = params[:id]
    @major = Major.find(params[:id])
    # @major=Major.find(params[:id])
    course = Course.find_by_cno(params[:cno])
    @item.course_id = course.id
    @item.compulsory = params[:compulsory]
    @item.credit = params[:credit]
    @item.start_time = params[:start_time]
    if @item.save
      redirect_to  major_path(@major)
    else
      redirect_to addcourse_majors_path
    end
  end

  # GET /majors or /majors.json
  def index
    @majors = Major.all
  end

  # GET /majors/1 or /majors/1.json
  def show
  end

  # GET /majors/new
  def new
    @major = Major.new
  end

  # GET /majors/1/edit
  def edit
  end

  # POST /majors or /majors.json
  def create
    @major = Major.new(major_params)

    respond_to do |format|
      if @major.save
        format.html { redirect_to major_url(@major), notice: "Major was successfully created." }
        format.json { render :show, status: :created, location: @major }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /majors/1 or /majors/1.json
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to major_url(@major), notice: "Major was successfully updated." }
        format.json { render :show, status: :ok, location: @major }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @major.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /majors/1 or /majors/1.json
  def destroy
    @major.destroy

    respond_to do |format|
      format.html { redirect_to majors_url, notice: "Major was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def major_params
      params.require(:major).permit(:name, :mno)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentDB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href=<%=root_path %>>首页</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <%#=link_to '学生列表' , students_path%>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href=<%=majors_path %>>专业</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=groups_path %>>班级</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=courses_path %>>课程</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=teachers_path %>>教师</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=students_path %>>学生</a>
        </li>
      </ul>
    </div>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          List
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href=<%=gradeinputshow_teachers_path %>>插入成绩</a>
          <a class="dropdown-item" href=<%=coursesetshow_teachers_path %>>开设课程</a>
        </div>
      </li>
    </ul>
    <%if current_admin %>
      <%= button_to "logout", destroy_admin_session_path, method: :delete, :class=>'btn btn-outline-success my-2 my-sm-0' %>
    <%end %>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
    <%if request.url!=root_url && request.url=='/admins/sign_in' %>
      <%=link_to '返回主页', root_path %>
    <%end %>
    <%#if current_admin %>
      <%#= button_to "logout", destroy_admin_session_path, method: :delete  %>
      <%#= button_to "AdminDashboard", 'y',method: :get  %>
    <%#end %>
  </body>

</html>